# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1947d6d670a7d91824dda1172075378207bb5c1bc901ba27053023dd807f69b8577ed64b02a9c41251b9c09f40fb55fdf5bf5e6da79990654db817cb97e4c461

test:
  secret_key_base: 69278f461f3256f0a8a24abf9532d6391669c249ea7e245b682e3ccd383e1d571f559fc13d448e8d2c796343aaf7c3d9f10c554995ee8a53e4f951509438c10e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
